[package]
name = "producer-consumer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = "0.36.2"
tokio = { version = "1.36.0", features = ["full"] }

[[bin]]
name = "producer"
path = "src/producer.rs"

[[bin]]
name = "consumer"
path = "src/consumer.rs"
